jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azure-pipelines-ci.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: azure-pipelines-ci.yml
  